---
coverage:
  status:
    project:
      server:
        paths:
          - server
        informational: true
      client:
        paths:
          - client
        informational: true
    patch:
      project:
        server:
          paths:
            - server
          informational: true
        client:
          paths:
            - client
          informational: true
