# ReadToday server base URI template
server_uri = "http://%s:%s"

# URI to which Google's authorization server sends a response.
oauth_redirect_uri = "http://127.0.0.1:38492"

[jdbc]
driver = "com.mysql.cj.jdbc.Driver"
# JDBC URL template
url = "jdbc:mysql://%s:%s/%s?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
