---
name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Java Code Base (server)
        run: |
          cd server
          mvn checkstyle:check -DcheckstyleViolationSeverity=warning
      - name: Lint Java Code Base (client)
        run: |
          cd client
          mvn checkstyle:check -DcheckstyleViolationSeverity=warning
