---
name: Publish docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Install Doxygen & Graphviz
        run: |
          sudo apt-get install -y doxygen
          sudo apt-get install -y graphviz
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Doxygen (server)
        run: mvn -f ./server/pom.xml --batch-mode --update-snapshots doxygen:report
      - name: Run Doxygen (client)
        run: mvn -f ./client/pom.xml --batch-mode --update-snapshots doxygen:report
      - name: Prepare docs page
        run: mvn -f ./pom.xml --batch-mode --update-snapshots resources:copy-resources@copy-doxygen-server resources:copy-resources@copy-doxygen-client
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './docs'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
